# Web Mining Menggunakan Trafilatura

## Pengumpulan Data Artikel Wikipedia

Pada praktikum ini dilakukan proses pengumpulan data dari Wikipedia menggunakan teknik web mining. Data yang dikumpulkan berupa 200 artikel dari Wikipedia.

Proses pengumpulan data dilakukan menggunakan Python, requests, dan Trafilatura. Setiap artikel akan diekstraksi menjadi data terstruktur yang terdiri dari judul, URL, teks artikel, dan jumlah kata.

In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 39.2 MB/s  0:00:00ta 0:00:01
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 43.6 MB/s  0:00:00s eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.5

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: /workspaces/PPW/envwebmining/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import requests
import trafilatura
import pandas as pd
import time
import re

print("Library berhasil diimpor")

Library berhasil diimpor

## 1. Sumber Data

Sumber data yang digunakan dalam praktikum ini adalah Wikipedia Bahasa Indonesia.

Wikipedia digunakan sebagai sumber data karena artikel dapat diakses secara bebas melalui internet. Data yang dikumpulkan berupa artikel Wikipedia yang diperoleh melalui API Wikipedia.

Pada praktikum ini akan dikumpulkan sebanyak 200 artikel. Setiap artikel akan memiliki informasi berupa judul, URL, isi teks, dan jumlah kata.

In [5]:
api_url = "https://id.wikipedia.org/w/api.php"

params = {
    "action": "query",
    "list": "search",
    "srsearch": "teknologi",
    "srnamespace": 0,
    "srlimit": 200,
    "format": "json"
}

headers = {
    "User-Agent": "WebMiningStudent/1.0 (educational project)"
}

response = requests.get(
    api_url,
    params=params,
    headers=headers,
    timeout=30
)

print("Status Code:", response.status_code)

Status Code: 200

In [6]:
data = response.json()

hasil_pencarian = data["query"]["search"]

print("Jumlah artikel ditemukan:", len(hasil_pencarian))

Jumlah artikel ditemukan: 200

In [7]:
hasil_data = []

headers = {
    "User-Agent": "WebMiningStudent/1.0 (educational project)"
}

print("Persiapan ekstraksi selesai")

Persiapan ekstraksi selesai

In [9]:
api_url = "https://id.wikipedia.org/w/api.php"

params = {
    "action": "query",
    "list": "search",
    "srsearch": "teknologi",
    "srnamespace": 0,
    "srlimit": 200,
    "format": "json"
}

headers = {
    "User-Agent": "WebMiningStudent/1.0 (educational project)"
}

response = requests.get(
    api_url,
    params=params,
    headers=headers,
    timeout=30
)

print("Status Code:", response.status_code)

data = response.json()
hasil_pencarian = data["query"]["search"]

print("Jumlah artikel ditemukan:", len(hasil_pencarian))

Status Code: 200
Jumlah artikel ditemukan: 200

In [10]:
daftar_url = []

for item in hasil_pencarian:
    judul = item["title"]
    url = "https://id.wikipedia.org/wiki/" + judul.replace(" ", "_")
    
    daftar_url.append({
        "judul": judul,
        "url": url
    })

print("Jumlah URL:", len(daftar_url))

Jumlah URL: 200

In [11]:
hasil_data = []

print("Mulai proses ekstraksi...")

Mulai proses ekstraksi...

In [12]:
for i, item in enumerate(daftar_url, start=1):
    judul = item["judul"]
    url = item["url"]

    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=30
        )

        if response.status_code == 200:
            html = response.text

            teks = trafilatura.extract(
                html,
                include_comments=False,
                include_tables=False
            )

            if teks:
                jumlah_kata = len(teks.split())

                hasil_data.append({
                    "id": i,
                    "judul": judul,
                    "url": url,
                    "teks": teks,
                    "jumlah_kata": jumlah_kata
                })

                print(f"{i}/200 berhasil: {judul}")
            else:
                print(f"{i}/200 teks tidak ditemukan: {judul}")

        else:
            print(f"{i}/200 gagal ({response.status_code}): {judul}")

        time.sleep(0.5)

    except Exception as e:
        print(f"{i}/200 error: {e}")

1/200 berhasil: Teknologi
2/200 berhasil: Halaman Utama
3/200 berhasil: Sejarah teknologi
4/200 berhasil: Institut Teknologi Bandung
5/200 berhasil: YouTube
6/200 berhasil: Google
7/200 berhasil: Teknologi informasi komunikasi
8/200 berhasil: B. J. Habibie
9/200 berhasil: Kementerian Pendidikan Tinggi, Sains, dan Teknologi Republik Indonesia
10/200 berhasil: Teknologi informasi
11/200 berhasil: Teknologi finansial
12/200 berhasil: Sumatera Utara
13/200 berhasil: Yandex
14/200 berhasil: Kesehatan
15/200 berhasil: Teknologi pendidikan
16/200 berhasil: Informatika
17/200 berhasil: Teknologi olahraga
18/200 berhasil: Institut Teknologi Sepuluh Nopember
19/200 berhasil: Elang Mahkota Teknologi
20/200 berhasil: Tahap kesiapan teknologi
21/200 berhasil: Daerah Istimewa Yogyakarta
22/200 berhasil: Revolusi Digital
23/200 berhasil: Badan Pengkajian dan Penerapan Teknologi
24/200 berhasil: Universitas Teknologi Bandung
25/200 berhasil: Teknologi informasi Indonesia
26/200 berhasil: Luhut Binsar Pandjaitan
27/200 berhasil: Sains dan teknologi di Indonesia
28/200 berhasil: Daftar Menteri Riset dan Teknologi Indonesia
29/200 berhasil: Kecerdasan buatan
30/200 berhasil: Energi surya
31/200 berhasil: Kementerian Riset dan Teknologi Republik Indonesia
32/200 berhasil: Desa
33/200 berhasil: Balai Layanan Platform Teknologi
34/200 berhasil: Universitas Brawijaya
35/200 berhasil: Revolusi Industri
36/200 berhasil: Teknologi nuklir
37/200 berhasil: 5G
38/200 berhasil: Windows Vista
39/200 berhasil: Richardus Eko Indrajit
40/200 berhasil: Reini Wirahadikusumah
41/200 berhasil: Teknologi komunikasi digital
42/200 berhasil: Yassierli
43/200 berhasil: Teknologi dan masyarakat
44/200 berhasil: Teknologi kesehatan
45/200 berhasil: Video
46/200 berhasil: Telkomsel
47/200 berhasil: Universitas Indonesia
48/200 berhasil: Uni Soviet
49/200 berhasil: Perdagangan elektronik
50/200 berhasil: Teknologi nuklir di Indonesia
51/200 berhasil: Tap Talk Teknologi
52/200 berhasil: Honda PCX
53/200 berhasil: Universitas Gadjah Mada
54/200 berhasil: Brian Yuliarto
55/200 berhasil: Teknologi pertanian
56/200 berhasil: Teknologi seluler
57/200 berhasil: Teknologi pengajaran
58/200 berhasil: Teknologi pangan
59/200 berhasil: Pengangguran teknologi
60/200 berhasil: Teknologi hijau
61/200 berhasil: Ricky Elson
62/200 berhasil: Generasi Z
63/200 berhasil: Antropologi teknologi
64/200 berhasil: Pusat kesehatan masyarakat
65/200 berhasil: Polytron
66/200 berhasil: Determinisme teknologi
67/200 berhasil: Teknologi militer
68/200 berhasil: Teknologi siluman
69/200 berhasil: Hammam Riza
70/200 berhasil: Universitas Teknologi Rhein Westfalen Aachen
71/200 berhasil: Teknologi pencari
72/200 berhasil: Institut Pertanian Bogor
73/200 berhasil: Teknologi tinggi
74/200 berhasil: Teknologi buku
75/200 berhasil: Lembaga Pendidikan dan Pelatihan Kepolisian Negara Republik Indonesia
76/200 berhasil: Mohammad Nuh
77/200 berhasil: Universitas Telkom
78/200 berhasil: Taxi Maxim
79/200 berhasil: Kementerian Pendidikan Dasar dan Menengah Republik Indonesia
80/200 berhasil: Institut Teknologi Sumatera
81/200 berhasil: Tatacipta Dirgantara
82/200 berhasil: Daftar pusat teknologi
83/200 berhasil: Pidi Baiq
84/200 berhasil: Industri 4.0
85/200 berhasil: Bambang Brodjonegoro
86/200 berhasil: Universitas Sanata Dharma
87/200 berhasil: Teknokrasi
88/200 berhasil: School on Internet Asia
89/200 berhasil: Budaya
90/200 berhasil: Teknologi berbasis listrik
91/200 berhasil: Telekomunikasi seluler di Indonesia
92/200 berhasil: Universitas Andalas
93/200 berhasil: Telekomunikasi
94/200 berhasil: Lambang Tut Wuri Handayani
95/200 berhasil: Roket
96/200 berhasil: Kertas elektronik
97/200 berhasil: Pengaruh teknologi terhadap anak-anak
98/200 berhasil: Revolusi Industri Keempat
99/200 berhasil: Sains dan teknologi di Filipina
100/200 berhasil: Dioda pemancar cahaya organik
101/200 berhasil: Produksi
102/200 berhasil: Teknologi kuno
103/200 berhasil: Waring Wera Wanua
104/200 berhasil: Apple Inc.
105/200 berhasil: Teknologi imersif
106/200 berhasil: Zaman Informasi
107/200 berhasil: Politeknik Teknologi Nuklir
108/200 berhasil: Wakil Menteri Pendidikan Tinggi, Sains, dan Teknologi Indonesia
109/200 berhasil: Institut Teknologi Garut
110/200 berhasil: Eri Cahyadi
111/200 berhasil: Tabung sinar katode
112/200 berhasil: Tarrasmart Teknologi Indonesia
113/200 berhasil: Institut Teknologi Kalimantan
114/200 berhasil: Teknologi musik
115/200 berhasil: Evolusi Jangka Panjang
116/200 berhasil: Institut Teknologi dan Bisnis Ahmad Dahlan Lamongan
117/200 berhasil: Hedy Lamarr
118/200 berhasil: Papan tulis interaktif
119/200 berhasil: Audi
120/200 berhasil: Institut Teknologi Nasional Bandung
121/200 berhasil: Prasanti Widyasih Sarli
122/200 berhasil: Kode Morse
123/200 berhasil: Perusahaan teknologi
124/200 berhasil: Purnomo Yusgiantoro
125/200 berhasil: Agroindustri
126/200 berhasil: 4G
127/200 berhasil: Pemanufakturan
128/200 berhasil: Organisasi Siswa Intra Sekolah
129/200 berhasil: Institut Teknologi Tangerang Selatan
130/200 berhasil: Sekolah Tinggi Ilmu Kepolisian
131/200 berhasil: Ilmu
132/200 berhasil: William Tanuwijaya
133/200 berhasil: Digitisasi
134/200 berhasil: Permainan
135/200 berhasil: Teknologi tepat guna
136/200 berhasil: Onno W. Purbo
137/200 berhasil: Alexander Graham Bell
138/200 berhasil: Cakram keras
139/200 berhasil: Perguruan Tinggi Negeri Badan Hukum
140/200 berhasil: Unduh
141/200 berhasil: Badan Tenaga Atom Internasional
142/200 berhasil: Institut Teknologi Massachusetts
143/200 berhasil: Soemantri Brodjonegoro
144/200 berhasil: Perangkat keras
145/200 berhasil: 1G
146/200 berhasil: Pusat panggilan
147/200 berhasil: Zulkieflimansyah
148/200 berhasil: Televisi
149/200 berhasil: Roosseno Soerjohadikoesoemo
150/200 berhasil: Nadiem Makarim
151/200 berhasil: Belva Devara
152/200 berhasil: Menteri Pendidikan Tinggi, Sains, dan Teknologi Indonesia
153/200 berhasil: Universitas Jenderal Soedirman
154/200 berhasil: Global System for Mobile Communications
155/200 berhasil: Achmad Zaky
156/200 berhasil: Komputer
157/200 berhasil: Puteri Indonesia
158/200 berhasil: Muhammad Romahurmuziy
159/200 berhasil: Komputasi awan
160/200 berhasil: Masyarakat Jaringan
161/200 berhasil: Rachmad Gobel
162/200 berhasil: Korps Lalu Lintas
163/200 berhasil: Neuroteknologi
164/200 berhasil: Kementerian Pertahanan Republik Indonesia
165/200 berhasil: Teknologi industri
166/200 berhasil: BMW
167/200 berhasil: Universitas Kristen Satya Wacana
168/200 berhasil: Kulkas
169/200 berhasil: Smartfren
170/200 berhasil: Badan Pengembangan dan Pembinaan Bahasa
171/200 berhasil: Bioteknologi
172/200 berhasil: Anime
173/200 berhasil: Sejarah radio
174/200 berhasil: Komunikasi teknologi
175/200 berhasil: Ridwan Kamil
176/200 berhasil: Gelembung dot-com
177/200 berhasil: Rantai blok
178/200 berhasil: Universitas Trisakti
179/200 berhasil: Modernisasi
180/200 berhasil: Sains, Teknologi, Rekayasa, dan Matematika
181/200 berhasil: WiMAX
182/200 berhasil: Otto Toto Sugiri
183/200 berhasil: Toshiba
184/200 berhasil: Transformasi digital
185/200 berhasil: Nurhayati Subakat
186/200 berhasil: Mobil
187/200 berhasil: Sistem informasi
188/200 berhasil: Institut Teknologi Petroleum Balongan
189/200 berhasil: Institut Teknologi PLN
190/200 berhasil: Institut Teknologi Nasional Malang
191/200 berhasil: Daftar Menteri Pendidikan Dasar dan Menengah Indonesia
192/200 berhasil: Jaringan area lokal
193/200 berhasil: I Nyoman Nuarta
194/200 berhasil: Institut Teknologi Padang
195/200 berhasil: Ilham Akbar Habibie
196/200 berhasil: Set-top box
197/200 berhasil: Magister
198/200 berhasil: Energi berkelanjutan
199/200 berhasil: Shenzhen
200/200 berhasil: MotoGP

In [13]:
df = pd.DataFrame(hasil_data)

print("Jumlah data berhasil:", len(df))

Jumlah data berhasil: 200

In [14]:
df = pd.DataFrame(hasil_data)

print("Jumlah data berhasil:", len(df))

Jumlah data berhasil: 200

In [15]:
df.head()

,id,judul,url,teks,jumlah_kata
0,1,Teknologi,https://id.wikipedia.org/wiki/Teknologi,Teknologi\nTeknologi adalah penerapan pengetah...,10844
1,2,Halaman Utama,https://id.wikipedia.org/wiki/Halaman_Utama,Halaman Utama\nArtikel pilihan\nArchaeopteryx ...,464
2,3,Sejarah teknologi,https://id.wikipedia.org/wiki/Sejarah_teknologi,Sejarah teknologi\nSejarah teknologi mencakup ...,3259
3,4,Institut Teknologi Bandung,https://id.wikipedia.org/wiki/Institut_Teknolo...,Institut Teknologi Bandung\nInstitut Teknologi...,6661
4,5,YouTube,https://id.wikipedia.org/wiki/YouTube,YouTube\nYouTube adalah sebuah situs web berba...,9448

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           200 non-null    int64
 1   judul        200 non-null    str
 2   url          200 non-null    str
 3   teks         200 non-null    str
 4   jumlah_kata  200 non-null    int64
dtypes: int64(2), str(3)
memory usage: 7.9 KB

In [17]:
print("Jumlah baris:", len(df))
print("Jumlah kolom:", len(df.columns))

Jumlah baris: 200
Jumlah kolom: 5

In [18]:
df["jumlah_kata"].describe()

count      200.000000
mean      2508.250000
std       2938.531837
min        154.000000
25%        826.500000
50%       1407.500000
75%       2644.250000
max      23678.000000
Name: jumlah_kata, dtype: float64

In [19]:
df.sort_values(
    by="jumlah_kata",
    ascending=False
)[["judul", "jumlah_kata"]].head(10)

                                        judul  jumlah_kata
103                                Apple Inc.        23678
130                                      Ilmu        15424
0                                   Teknologi        10844
22   Badan Pengkajian dan Penerapan Teknologi        10721
176                               Rantai blok        10373
61                                 Generasi Z         9664
4                                     YouTube         9448
168                                 Smartfren         9398
14                       Teknologi pendidikan         8740
152            Universitas Jenderal Soedirman         8662

In [20]:
df.sort_values(
    by="jumlah_kata",
    ascending=True
)[["judul", "jumlah_kata"]].head(10)

                          judul  jumlah_kata
97    Revolusi Industri Keempat          154
122        Perusahaan teknologi          164
43          Teknologi kesehatan          242
164          Teknologi industri          244
72             Teknologi tinggi          281
144                          1G          298
93   Lambang Tut Wuri Handayani          303
108    Institut Teknologi Garut          311
105             Zaman Informasi          347
175           Gelembung dot-com          367

In [21]:
df.to_csv(
    "data_200_wikipedia.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset berhasil disimpan.")

Dataset berhasil disimpan.