# Tugas 1

In [1]:
%pip install requests beautifulsoup4 trafilatura pandas openpyxl tqdm

Requirement already satisfied: requests in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (4.15.0)
Requirement already satisfied: trafilatura in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (2.2.0)
Requirement already satisfied: pandas in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: openpyxl in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: tqdm in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (4.70.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: courlan>=1.4.0 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from trafilatura) (1.4.0)
Requirement already satisfied: htmldate>=1.10.0 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from trafilatura) (1.10.0)
Requirement already satisfied: justext>=3.0.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from trafilatura) (3.0.2)
Requirement already satisfied: lxml>=6.1.1 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from trafilatura) (6.1.3)
Requirement already satisfied: numpy>=2.3.3 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: babel>=2.16.0 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from courlan>=1.4.0->trafilatura) (2.18.0)
Requirement already satisfied: tld>=0.13 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from courlan>=1.4.0->trafilatura) (0.13.2)
Requirement already satisfied: dateparser>=1.1.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from htmldate>=1.10.0->trafilatura) (1.4.3)
Requirement already satisfied: pytz>=2024.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from dateparser>=1.1.2->htmldate>=1.10.0->trafilatura) (2026.3.post1)
Requirement already satisfied: regex>=2024.9.11 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from dateparser>=1.1.2->htmldate>=1.10.0->trafilatura) (2026.9.3)
Requirement already satisfied: tzlocal>=0.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from dateparser>=1.1.2->htmldate>=1.10.0->trafilatura) (5.4.4)
Requirement already satisfied: lxml_html_clean in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from lxml[html_clean]>=4.4.2->justext>=3.0.2->trafilatura) (0.4.5)
Requirement already satisfied: six>=1.5 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import re
import time
import random
import requests
import pandas as pd
import trafilatura

from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlsplit, urlunsplit
from tqdm import tqdm

In [3]:
# ============================================================
# 1. KONFIGURASI
# ============================================================

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/152.0 Safari/537.36"
    )
}

session = requests.Session()
session.headers.update(HEADERS)

kategori = {
    "sport": {
        "url": "https://sport.detik.com/indeks",
        "domain": "sport.detik.com"
    },
    "finance": {
        "url": "https://finance.detik.com/indeks",
        "domain": "finance.detik.com"
    }
}
print("Konfigurasi berhasil")
print("Sport :", kategori["sport"]["url"])
print("Finance:", kategori["finance"]["url"])

Konfigurasi berhasil
Sport : https://sport.detik.com/indeks
Finance: https://finance.detik.com/indeks

In [4]:
def normalize_url(url):
    """
    Menghapus query parameter dan fragment dari URL.
    """
    bagian = urlsplit(url)

    url_bersih = urlunsplit(
        (
            bagian.scheme,
            bagian.netloc,
            bagian.path,
            "",
            ""
        )
    )

    return url_bersih

In [5]:
def ambil_link_berita(index_url, domain, target=150, max_page=20):
    links = []
    sudah_ada = set()

    for page in range(1, max_page + 1):
        url_page = f"{index_url}?page={page}"

        print(f"Membaca halaman {page}")

        try:
            response = session.get(
                url_page,
                timeout=20
            )

            response.raise_for_status()

        except Exception as e:
            print("Error:", e)
            continue

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        for tag in soup.find_all("a", href=True):

            href = urljoin(
                url_page,
                tag["href"]
            )

            href = normalize_url(href)

            parsed = urlsplit(href)

            # URL artikel Detik biasanya memiliki /d-xxxx
            if (
                parsed.netloc == domain
                and re.search(r"/d-\d+", parsed.path)
            ):

                if href not in sudah_ada:
                    sudah_ada.add(href)
                    links.append(href)

        print(
            "Jumlah link:",
            len(links)
        )

        if len(links) >= target:
            break

        # delay
        time.sleep(
            random.uniform(1, 2)
        )

    return links

In [6]:
link_sport = ambil_link_berita(
    kategori["sport"]["url"],
    kategori["sport"]["domain"],
    target=150
)

print(
    "Total kandidat Sport:",
    len(link_sport)
)

Membaca halaman 1
Jumlah link: 20
Membaca halaman 2
Jumlah link: 39
Membaca halaman 3
Jumlah link: 57
Membaca halaman 4
Jumlah link: 77
Membaca halaman 5
Jumlah link: 97
Membaca halaman 6
Jumlah link: 117
Membaca halaman 7
Jumlah link: 137
Membaca halaman 8
Jumlah link: 157
Total kandidat Sport: 157

In [7]:
link_finance = ambil_link_berita(
    kategori["finance"]["url"],
    kategori["finance"]["domain"],
    target=150
)

print(
    "Total kandidat Finance:",
    len(link_finance)
)

Membaca halaman 1
Jumlah link: 17
Membaca halaman 2
Jumlah link: 35
Membaca halaman 3
Jumlah link: 55
Membaca halaman 4
Jumlah link: 74
Membaca halaman 5
Jumlah link: 91
Membaca halaman 6
Jumlah link: 110
Membaca halaman 7
Jumlah link: 130
Membaca halaman 8
Jumlah link: 147
Membaca halaman 9
Jumlah link: 162
Total kandidat Finance: 162

In [8]:
link_finance = ambil_link_berita(
    kategori["finance"]["url"],
    kategori["finance"]["domain"],
    target=150
)

print(
    "Total kandidat Finance:",
    len(link_finance)
)

Membaca halaman 1
Jumlah link: 17
Membaca halaman 2
Jumlah link: 35
Membaca halaman 3
Jumlah link: 55
Membaca halaman 4
Jumlah link: 74
Membaca halaman 5
Jumlah link: 91
Membaca halaman 6
Jumlah link: 110
Membaca halaman 7
Jumlah link: 130
Membaca halaman 8
Jumlah link: 147
Membaca halaman 9
Jumlah link: 162
Total kandidat Finance: 162

In [9]:
def scraping_kategori(
    links,
    label,
    target=100
):
    hasil = []

    for url in tqdm(
        links,
        desc=f"Scraping {label}"
    ):

        if len(hasil) >= target:
            break

        isi = ambil_isi_berita(url)

        if isi is not None:
            hasil.append(
                {
                    "isi_berita": isi,
                    "label": label
                }
            )

        # Delay supaya tidak terlalu cepat
        time.sleep(
            random.uniform(1, 2)
        )

        print(
            f"{label} berhasil:",
            len(hasil)
        )

    return hasil

In [10]:
def bersihkan_teks(teks):
    if teks is None:
        return None

    teks = re.sub(
        r"ADVERTISEMENT",
        " ",
        teks,
        flags=re.IGNORECASE
    )

    teks = re.sub(
        r"SCROLL TO CONTINUE WITH CONTENT",
        " ",
        teks,
        flags=re.IGNORECASE
    )

    teks = re.sub(
        r"\s+",
        " ",
        teks
    )

    return teks.strip()

In [11]:
def ambil_isi_berita(url):
    try:
        response = session.get(
            url,
            timeout=25
        )

        response.raise_for_status()

        isi = trafilatura.extract(
            response.text,
            include_comments=False,
            include_tables=False,
            output_format="txt",
            favor_precision=True,
            deduplicate=True
        )

        isi = bersihkan_teks(isi)

        if isi and len(isi) >= 300:
            return isi

    except Exception as e:
        print("Gagal:", url)
        print("Error:", e)

    return None

In [12]:
data_sport = scraping_kategori(
    link_sport,
    "sport",
    target=100
)

Scraping sport:   1%|▍                                                              | 1/157 [00:01<03:47,  1.46s/it]

sport berhasil: 0

Scraping sport:   1%|▊                                                              | 2/157 [00:03<04:36,  1.79s/it]

sport berhasil: 1

Scraping sport:   2%|█▏                                                             | 3/157 [00:05<04:47,  1.87s/it]

sport berhasil: 2

Scraping sport:   3%|█▌                                                             | 4/157 [00:06<04:21,  1.71s/it]

sport berhasil: 3

Scraping sport:   3%|██                                                             | 5/157 [00:08<04:13,  1.66s/it]

sport berhasil: 4

Scraping sport:   4%|██▍                                                            | 6/157 [00:10<04:31,  1.79s/it]

sport berhasil: 5

Scraping sport:   4%|██▊                                                            | 7/157 [00:12<04:42,  1.88s/it]

sport berhasil: 6

Scraping sport:   5%|███▏                                                           | 8/157 [00:14<04:49,  1.95s/it]

sport berhasil: 7

Scraping sport:   6%|███▌                                                           | 9/157 [00:16<04:20,  1.76s/it]

sport berhasil: 8

Scraping sport:   6%|███▉                                                          | 10/157 [00:18<04:32,  1.85s/it]

sport berhasil: 9

Scraping sport:   7%|████▎                                                         | 11/157 [00:20<04:34,  1.88s/it]

sport berhasil: 10

Scraping sport:   8%|████▋                                                         | 12/157 [00:22<04:49,  1.99s/it]

sport berhasil: 11

Scraping sport:   8%|█████▏                                                        | 13/157 [00:23<04:26,  1.85s/it]

sport berhasil: 12

Scraping sport:   9%|█████▌                                                        | 14/157 [00:26<04:43,  1.98s/it]

sport berhasil: 13

Scraping sport:  10%|█████▉                                                        | 15/157 [00:27<04:15,  1.80s/it]

sport berhasil: 14

Scraping sport:  10%|██████▎                                                       | 16/157 [00:29<04:06,  1.75s/it]

sport berhasil: 15

Scraping sport:  11%|██████▋                                                       | 17/157 [00:30<03:59,  1.71s/it]

sport berhasil: 16

Scraping sport:  11%|███████                                                       | 18/157 [00:32<03:59,  1.73s/it]

sport berhasil: 17

Scraping sport:  12%|███████▌                                                      | 19/157 [00:34<04:25,  1.92s/it]

sport berhasil: 18

Scraping sport:  13%|███████▉                                                      | 20/157 [00:36<04:23,  1.92s/it]

sport berhasil: 19

Scraping sport:  13%|████████▎                                                     | 21/157 [00:38<04:16,  1.88s/it]

sport berhasil: 20

Scraping sport:  14%|████████▋                                                     | 22/157 [00:40<04:24,  1.96s/it]

sport berhasil: 21

Scraping sport:  15%|█████████                                                     | 23/157 [00:41<03:55,  1.76s/it]

sport berhasil: 22

Scraping sport:  15%|█████████▍                                                    | 24/157 [00:44<04:10,  1.88s/it]

sport berhasil: 23

Scraping sport:  16%|█████████▊                                                    | 25/157 [00:45<04:02,  1.84s/it]

sport berhasil: 24

Scraping sport:  17%|██████████▎                                                   | 26/157 [00:47<03:51,  1.77s/it]

sport berhasil: 25

Scraping sport:  17%|██████████▋                                                   | 27/157 [00:48<03:35,  1.65s/it]

sport berhasil: 26

Scraping sport:  18%|███████████                                                   | 28/157 [00:51<03:54,  1.81s/it]

sport berhasil: 27

Scraping sport:  18%|███████████▍                                                  | 29/157 [00:53<04:00,  1.88s/it]

sport berhasil: 28

Scraping sport:  19%|███████████▊                                                  | 30/157 [00:54<03:39,  1.73s/it]

sport berhasil: 29

Scraping sport:  20%|████████████▏                                                 | 31/157 [00:56<03:41,  1.76s/it]

sport berhasil: 30

Scraping sport:  20%|████████████▋                                                 | 32/157 [00:57<03:33,  1.71s/it]

sport berhasil: 31

Scraping sport:  21%|█████████████                                                 | 33/157 [00:59<03:40,  1.78s/it]

sport berhasil: 32

Scraping sport:  22%|█████████████▍                                                | 34/157 [01:01<03:41,  1.80s/it]

sport berhasil: 33

Scraping sport:  22%|█████████████▊                                                | 35/157 [01:03<03:21,  1.65s/it]

sport berhasil: 34

Scraping sport:  23%|██████████████▏                                               | 36/157 [01:04<03:26,  1.71s/it]

sport berhasil: 35

Scraping sport:  24%|██████████████▌                                               | 37/157 [01:07<03:43,  1.86s/it]

sport berhasil: 36

Scraping sport:  24%|███████████████                                               | 38/157 [01:09<03:53,  1.96s/it]

sport berhasil: 36

Scraping sport:  25%|███████████████▍                                              | 39/157 [01:11<04:05,  2.08s/it]

sport berhasil: 37

Scraping sport:  25%|███████████████▊                                              | 40/157 [01:13<03:48,  1.95s/it]

sport berhasil: 38

Scraping sport:  26%|████████████████▏                                             | 41/157 [01:14<03:35,  1.86s/it]

sport berhasil: 39

Scraping sport:  27%|████████████████▌                                             | 42/157 [01:16<03:37,  1.89s/it]

sport berhasil: 40

Scraping sport:  27%|████████████████▉                                             | 43/157 [01:18<03:33,  1.87s/it]

sport berhasil: 41

Scraping sport:  28%|█████████████████▍                                            | 44/157 [01:20<03:41,  1.96s/it]

sport berhasil: 42

Scraping sport:  29%|█████████████████▊                                            | 45/157 [01:22<03:39,  1.96s/it]

sport berhasil: 43

Scraping sport:  29%|██████████████████▏                                           | 46/157 [01:24<03:31,  1.90s/it]

sport berhasil: 44

Scraping sport:  30%|██████████████████▌                                           | 47/157 [01:26<03:19,  1.81s/it]

sport berhasil: 45

Scraping sport:  31%|██████████████████▉                                           | 48/157 [01:27<03:11,  1.76s/it]

sport berhasil: 46

Scraping sport:  31%|███████████████████▎                                          | 49/157 [01:29<03:19,  1.85s/it]

sport berhasil: 47

Scraping sport:  32%|███████████████████▋                                          | 50/157 [01:31<03:02,  1.71s/it]

sport berhasil: 48

Scraping sport:  32%|████████████████████▏                                         | 51/157 [01:33<03:17,  1.87s/it]

sport berhasil: 48

Scraping sport:  33%|████████████████████▌                                         | 52/157 [01:35<03:24,  1.95s/it]

sport berhasil: 49

Scraping sport:  34%|████████████████████▉                                         | 53/157 [01:37<03:06,  1.79s/it]

sport berhasil: 50

Scraping sport:  34%|█████████████████████▎                                        | 54/157 [01:38<02:51,  1.67s/it]

sport berhasil: 51

Scraping sport:  35%|█████████████████████▋                                        | 55/157 [01:40<02:53,  1.70s/it]

sport berhasil: 52

Scraping sport:  36%|██████████████████████                                        | 56/157 [01:42<03:05,  1.84s/it]

sport berhasil: 53

Scraping sport:  36%|██████████████████████▌                                       | 57/157 [01:44<03:16,  1.96s/it]

sport berhasil: 54

Scraping sport:  37%|██████████████████████▉                                       | 58/157 [01:47<03:25,  2.08s/it]

sport berhasil: 55

Scraping sport:  38%|███████████████████████▎                                      | 59/157 [01:48<03:16,  2.00s/it]

sport berhasil: 56

Scraping sport:  38%|███████████████████████▋                                      | 60/157 [01:50<03:15,  2.02s/it]

sport berhasil: 57

Scraping sport:  39%|████████████████████████                                      | 61/157 [01:52<03:06,  1.94s/it]

sport berhasil: 58

Scraping sport:  39%|████████████████████████▍                                     | 62/157 [01:54<03:07,  1.98s/it]

sport berhasil: 59

Scraping sport:  40%|████████████████████████▉                                     | 63/157 [01:56<02:59,  1.91s/it]

sport berhasil: 60

Scraping sport:  41%|█████████████████████████▎                                    | 64/157 [01:58<03:06,  2.00s/it]

sport berhasil: 61

Scraping sport:  41%|█████████████████████████▋                                    | 65/157 [02:00<03:08,  2.05s/it]

sport berhasil: 62

Scraping sport:  42%|██████████████████████████                                    | 66/157 [02:02<02:51,  1.88s/it]

sport berhasil: 63

Scraping sport:  43%|██████████████████████████▍                                   | 67/157 [02:04<02:53,  1.93s/it]

sport berhasil: 64

Scraping sport:  43%|██████████████████████████▊                                   | 68/157 [02:06<02:53,  1.95s/it]

sport berhasil: 65

Scraping sport:  44%|███████████████████████████▏                                  | 69/157 [02:07<02:39,  1.81s/it]

sport berhasil: 66

Scraping sport:  45%|███████████████████████████▋                                  | 70/157 [02:09<02:45,  1.91s/it]

sport berhasil: 67

Scraping sport:  45%|████████████████████████████                                  | 71/157 [02:12<02:53,  2.02s/it]

sport berhasil: 68

Scraping sport:  46%|████████████████████████████▍                                 | 72/157 [02:14<02:49,  1.99s/it]

sport berhasil: 69

Scraping sport:  46%|████████████████████████████▊                                 | 73/157 [02:15<02:38,  1.89s/it]

sport berhasil: 70

Scraping sport:  47%|█████████████████████████████▏                                | 74/157 [02:17<02:29,  1.80s/it]

sport berhasil: 71

Scraping sport:  48%|█████████████████████████████▌                                | 75/157 [02:18<02:20,  1.72s/it]

sport berhasil: 72

Scraping sport:  48%|██████████████████████████████                                | 76/157 [02:20<02:22,  1.76s/it]

sport berhasil: 73

Scraping sport:  49%|██████████████████████████████▍                               | 77/157 [02:22<02:18,  1.74s/it]

sport berhasil: 74

Scraping sport:  50%|██████████████████████████████▊                               | 78/157 [02:23<02:08,  1.63s/it]

sport berhasil: 75

Scraping sport:  50%|███████████████████████████████▏                              | 79/157 [02:25<02:04,  1.60s/it]

sport berhasil: 76

Scraping sport:  51%|███████████████████████████████▌                              | 80/157 [02:26<02:01,  1.58s/it]

sport berhasil: 77

Scraping sport:  52%|███████████████████████████████▉                              | 81/157 [02:28<01:56,  1.54s/it]

sport berhasil: 78

Scraping sport:  52%|████████████████████████████████▍                             | 82/157 [02:30<02:00,  1.61s/it]

sport berhasil: 79

Scraping sport:  53%|████████████████████████████████▊                             | 83/157 [02:32<02:06,  1.71s/it]

sport berhasil: 80

Scraping sport:  54%|█████████████████████████████████▏                            | 84/157 [02:33<02:07,  1.75s/it]

sport berhasil: 81

Scraping sport:  54%|█████████████████████████████████▌                            | 85/157 [02:35<02:08,  1.78s/it]

sport berhasil: 82

Scraping sport:  55%|█████████████████████████████████▉                            | 86/157 [02:37<02:00,  1.70s/it]

sport berhasil: 83

Scraping sport:  55%|██████████████████████████████████▎                           | 87/157 [02:39<02:04,  1.78s/it]

sport berhasil: 83

Scraping sport:  56%|██████████████████████████████████▊                           | 88/157 [02:40<01:55,  1.67s/it]

sport berhasil: 84

Scraping sport:  57%|███████████████████████████████████▏                          | 89/157 [02:42<01:46,  1.57s/it]

sport berhasil: 85

Scraping sport:  57%|███████████████████████████████████▌                          | 90/157 [02:43<01:52,  1.68s/it]

sport berhasil: 86

Scraping sport:  58%|███████████████████████████████████▉                          | 91/157 [02:45<01:52,  1.70s/it]

sport berhasil: 87

Scraping sport:  59%|████████████████████████████████████▎                         | 92/157 [02:47<01:52,  1.72s/it]

sport berhasil: 88

Scraping sport:  59%|████████████████████████████████████▋                         | 93/157 [02:49<01:47,  1.67s/it]

sport berhasil: 89

Scraping sport:  60%|█████████████████████████████████████                         | 94/157 [02:50<01:45,  1.67s/it]

sport berhasil: 90

Scraping sport:  61%|█████████████████████████████████████▌                        | 95/157 [02:52<01:38,  1.59s/it]

sport berhasil: 91

Scraping sport:  61%|█████████████████████████████████████▉                        | 96/157 [02:53<01:35,  1.56s/it]

sport berhasil: 92

Scraping sport:  62%|██████████████████████████████████████▎                       | 97/157 [02:54<01:30,  1.51s/it]

sport berhasil: 93

Scraping sport:  62%|██████████████████████████████████████▋                       | 98/157 [02:56<01:30,  1.54s/it]

sport berhasil: 94

Scraping sport:  63%|███████████████████████████████████████                       | 99/157 [02:58<01:27,  1.50s/it]

sport berhasil: 95

Scraping sport:  64%|██████████████████████████████████████▊                      | 100/157 [03:00<01:34,  1.66s/it]

sport berhasil: 96

Scraping sport:  64%|███████████████████████████████████████▏                     | 101/157 [03:01<01:32,  1.66s/it]

sport berhasil: 97

Scraping sport:  65%|███████████████████████████████████████▋                     | 102/157 [03:03<01:30,  1.64s/it]

sport berhasil: 98

Scraping sport:  66%|████████████████████████████████████████                     | 103/157 [03:05<01:37,  1.80s/it]

sport berhasil: 99

Scraping sport:  66%|████████████████████████████████████████▍                    | 104/157 [03:07<01:35,  1.81s/it]

sport berhasil: 100

In [13]:
data_finance = scraping_kategori(
    link_finance,
    "finance",
    target=100
)

Scraping finance:   1%|▍                                                            | 1/162 [00:02<05:32,  2.06s/it]

finance berhasil: 1

Scraping finance:   1%|▊                                                            | 2/162 [00:04<05:27,  2.05s/it]

finance berhasil: 2

Scraping finance:   2%|█▏                                                           | 3/162 [00:06<05:27,  2.06s/it]

finance berhasil: 3

Scraping finance:   2%|█▌                                                           | 4/162 [00:07<04:54,  1.87s/it]

finance berhasil: 4

Scraping finance:   3%|█▉                                                           | 5/162 [00:09<04:42,  1.80s/it]

finance berhasil: 5

Scraping finance:   4%|██▎                                                          | 6/162 [00:10<04:18,  1.66s/it]

finance berhasil: 5

Scraping finance:   4%|██▋                                                          | 7/162 [00:12<04:22,  1.69s/it]

finance berhasil: 6

Scraping finance:   5%|███                                                          | 8/162 [00:14<04:32,  1.77s/it]

finance berhasil: 7

Scraping finance:   6%|███▍                                                         | 9/162 [00:15<04:14,  1.66s/it]

finance berhasil: 8

Scraping finance:   6%|███▋                                                        | 10/162 [00:18<04:41,  1.85s/it]

finance berhasil: 9

Scraping finance:   7%|████                                                        | 11/162 [00:20<04:47,  1.91s/it]

finance berhasil: 10

Scraping finance:   7%|████▍                                                       | 12/162 [00:22<04:51,  1.94s/it]

finance berhasil: 11

Scraping finance:   8%|████▊                                                       | 13/162 [00:24<04:44,  1.91s/it]

finance berhasil: 12

Scraping finance:   9%|█████▏                                                      | 14/162 [00:26<04:47,  1.94s/it]

finance berhasil: 13

Scraping finance:   9%|█████▌                                                      | 15/162 [00:27<04:32,  1.86s/it]

finance berhasil: 14

Scraping finance:  10%|█████▉                                                      | 16/162 [00:30<04:56,  2.03s/it]

finance berhasil: 15

Scraping finance:  10%|██████▎                                                     | 17/162 [00:32<05:06,  2.12s/it]

finance berhasil: 16

Scraping finance:  11%|██████▋                                                     | 18/162 [00:34<04:43,  1.97s/it]

finance berhasil: 17

Scraping finance:  12%|███████                                                     | 19/162 [00:35<04:24,  1.85s/it]

finance berhasil: 18

Scraping finance:  12%|███████▍                                                    | 20/162 [00:37<04:34,  1.93s/it]

finance berhasil: 19

Scraping finance:  13%|███████▊                                                    | 21/162 [00:39<04:28,  1.90s/it]

finance berhasil: 20

Scraping finance:  14%|████████▏                                                   | 22/162 [00:41<04:07,  1.77s/it]

finance berhasil: 21

Scraping finance:  14%|████████▌                                                   | 23/162 [00:42<04:08,  1.78s/it]

finance berhasil: 22

Scraping finance:  15%|████████▉                                                   | 24/162 [00:45<04:25,  1.93s/it]

finance berhasil: 23

Scraping finance:  15%|█████████▎                                                  | 25/162 [00:46<04:04,  1.78s/it]

finance berhasil: 24

Scraping finance:  16%|█████████▋                                                  | 26/162 [00:48<04:22,  1.93s/it]

finance berhasil: 25

Scraping finance:  17%|██████████                                                  | 27/162 [00:50<04:07,  1.83s/it]

finance berhasil: 26

Scraping finance:  17%|██████████▎                                                 | 28/162 [00:52<04:07,  1.84s/it]

finance berhasil: 27

Scraping finance:  18%|██████████▋                                                 | 29/162 [00:53<03:41,  1.67s/it]

finance berhasil: 28

Scraping finance:  19%|███████████                                                 | 30/162 [00:55<03:28,  1.58s/it]

finance berhasil: 29

Scraping finance:  19%|███████████▍                                                | 31/162 [00:56<03:28,  1.59s/it]

finance berhasil: 30

Scraping finance:  20%|███████████▊                                                | 32/162 [00:58<03:50,  1.77s/it]

finance berhasil: 31

Scraping finance:  20%|████████████▏                                               | 33/162 [01:00<03:56,  1.84s/it]

finance berhasil: 32

Scraping finance:  21%|████████████▌                                               | 34/162 [01:02<04:03,  1.90s/it]

finance berhasil: 32

Scraping finance:  22%|████████████▉                                               | 35/162 [01:04<03:52,  1.83s/it]

finance berhasil: 33

Scraping finance:  22%|█████████████▎                                              | 36/162 [01:06<03:47,  1.80s/it]

finance berhasil: 34

Scraping finance:  23%|█████████████▋                                              | 37/162 [01:07<03:27,  1.66s/it]

finance berhasil: 35

Scraping finance:  23%|██████████████                                              | 38/162 [01:09<03:34,  1.73s/it]

finance berhasil: 36

Scraping finance:  24%|██████████████▍                                             | 39/162 [01:11<03:49,  1.87s/it]

finance berhasil: 37

Scraping finance:  25%|██████████████▊                                             | 40/162 [01:13<03:35,  1.76s/it]

finance berhasil: 38

Scraping finance:  25%|███████████████▏                                            | 41/162 [01:15<03:43,  1.85s/it]

finance berhasil: 39

Scraping finance:  26%|███████████████▌                                            | 42/162 [01:16<03:33,  1.78s/it]

finance berhasil: 40

Scraping finance:  27%|███████████████▉                                            | 43/162 [01:18<03:17,  1.66s/it]

finance berhasil: 41

Scraping finance:  27%|████████████████▎                                           | 44/162 [01:20<03:27,  1.76s/it]

finance berhasil: 42

Scraping finance:  28%|████████████████▋                                           | 45/162 [01:22<03:40,  1.88s/it]

finance berhasil: 43

Scraping finance:  28%|█████████████████                                           | 46/162 [01:23<03:26,  1.78s/it]

finance berhasil: 44

Scraping finance:  29%|█████████████████▍                                          | 47/162 [01:25<03:12,  1.67s/it]

finance berhasil: 45

Scraping finance:  30%|█████████████████▊                                          | 48/162 [01:26<03:08,  1.65s/it]

finance berhasil: 46

Scraping finance:  30%|██████████████████▏                                         | 49/162 [01:28<03:02,  1.62s/it]

finance berhasil: 47

Scraping finance:  31%|██████████████████▌                                         | 50/162 [01:30<03:21,  1.80s/it]

finance berhasil: 47

Scraping finance:  31%|██████████████████▉                                         | 51/162 [01:32<03:07,  1.69s/it]

finance berhasil: 48

Scraping finance:  32%|███████████████████▎                                        | 52/162 [01:34<03:17,  1.80s/it]

finance berhasil: 49

Scraping finance:  33%|███████████████████▋                                        | 53/162 [01:36<03:25,  1.88s/it]

finance berhasil: 50

Scraping finance:  33%|████████████████████                                        | 54/162 [01:38<03:34,  1.99s/it]

finance berhasil: 51

Scraping finance:  34%|████████████████████▎                                       | 55/162 [01:40<03:22,  1.89s/it]

finance berhasil: 52

Scraping finance:  35%|████████████████████▋                                       | 56/162 [01:41<03:06,  1.76s/it]

finance berhasil: 53

Scraping finance:  35%|█████████████████████                                       | 57/162 [01:43<02:51,  1.64s/it]

finance berhasil: 54

Scraping finance:  36%|█████████████████████▍                                      | 58/162 [01:44<02:49,  1.63s/it]

finance berhasil: 55

Scraping finance:  36%|█████████████████████▊                                      | 59/162 [01:45<02:36,  1.52s/it]

finance berhasil: 56

Scraping finance:  37%|██████████████████████▏                                     | 60/162 [01:47<02:52,  1.69s/it]

finance berhasil: 57

Scraping finance:  38%|██████████████████████▌                                     | 61/162 [01:49<02:56,  1.75s/it]

finance berhasil: 58

Scraping finance:  38%|██████████████████████▉                                     | 62/162 [01:52<03:07,  1.87s/it]

finance berhasil: 59

Scraping finance:  39%|███████████████████████▎                                    | 63/162 [01:54<03:09,  1.91s/it]

finance berhasil: 60

Scraping finance:  40%|███████████████████████▋                                    | 64/162 [01:55<02:59,  1.83s/it]

finance berhasil: 61

Scraping finance:  40%|████████████████████████                                    | 65/162 [01:57<03:03,  1.89s/it]

finance berhasil: 62

Scraping finance:  41%|████████████████████████▍                                   | 66/162 [01:59<03:00,  1.88s/it]

finance berhasil: 63

Scraping finance:  41%|████████████████████████▊                                   | 67/162 [02:01<03:04,  1.95s/it]

finance berhasil: 64

Scraping finance:  42%|█████████████████████████▏                                  | 68/162 [02:03<03:11,  2.03s/it]

finance berhasil: 65

Scraping finance:  43%|█████████████████████████▌                                  | 69/162 [02:05<03:00,  1.94s/it]

finance berhasil: 66

Scraping finance:  43%|█████████████████████████▉                                  | 70/162 [02:07<02:54,  1.89s/it]

finance berhasil: 67

Scraping finance:  44%|██████████████████████████▎                                 | 71/162 [02:09<02:48,  1.85s/it]

finance berhasil: 68

Scraping finance:  44%|██████████████████████████▋                                 | 72/162 [02:10<02:30,  1.67s/it]

finance berhasil: 69

Scraping finance:  45%|███████████████████████████                                 | 73/162 [02:11<02:19,  1.57s/it]

finance berhasil: 70

Scraping finance:  46%|███████████████████████████▍                                | 74/162 [02:13<02:27,  1.67s/it]

finance berhasil: 71

Scraping finance:  46%|███████████████████████████▊                                | 75/162 [02:15<02:21,  1.63s/it]

finance berhasil: 72

Scraping finance:  47%|████████████████████████████▏                               | 76/162 [02:17<02:27,  1.71s/it]

finance berhasil: 73

Scraping finance:  48%|████████████████████████████▌                               | 77/162 [02:18<02:26,  1.73s/it]

finance berhasil: 74

Scraping finance:  48%|████████████████████████████▉                               | 78/162 [02:20<02:18,  1.65s/it]

finance berhasil: 75

Scraping finance:  49%|█████████████████████████████▎                              | 79/162 [02:21<02:15,  1.64s/it]

finance berhasil: 76

Scraping finance:  49%|█████████████████████████████▋                              | 80/162 [02:23<02:21,  1.73s/it]

finance berhasil: 77

Scraping finance:  50%|██████████████████████████████                              | 81/162 [02:26<02:33,  1.89s/it]

finance berhasil: 78

Scraping finance:  51%|██████████████████████████████▎                             | 82/162 [02:28<02:32,  1.91s/it]

finance berhasil: 79

Scraping finance:  51%|██████████████████████████████▋                             | 83/162 [02:29<02:24,  1.83s/it]

finance berhasil: 80

Scraping finance:  52%|███████████████████████████████                             | 84/162 [02:31<02:28,  1.91s/it]

finance berhasil: 81

Scraping finance:  52%|███████████████████████████████▍                            | 85/162 [02:34<02:33,  1.99s/it]

finance berhasil: 82

Scraping finance:  53%|███████████████████████████████▊                            | 86/162 [02:35<02:16,  1.79s/it]

finance berhasil: 83

Scraping finance:  54%|████████████████████████████████▏                           | 87/162 [02:36<02:02,  1.64s/it]

finance berhasil: 84

Scraping finance:  54%|████████████████████████████████▌                           | 88/162 [02:38<01:56,  1.57s/it]

finance berhasil: 85

Scraping finance:  55%|████████████████████████████████▉                           | 89/162 [02:40<02:06,  1.74s/it]

finance berhasil: 86

Scraping finance:  56%|█████████████████████████████████▎                          | 90/162 [02:42<02:09,  1.79s/it]

finance berhasil: 87

Scraping finance:  56%|█████████████████████████████████▋                          | 91/162 [02:43<02:03,  1.74s/it]

finance berhasil: 88

Scraping finance:  57%|██████████████████████████████████                          | 92/162 [02:45<01:54,  1.64s/it]

finance berhasil: 89

Scraping finance:  57%|██████████████████████████████████▍                         | 93/162 [02:46<01:49,  1.58s/it]

finance berhasil: 90

Scraping finance:  58%|██████████████████████████████████▊                         | 94/162 [02:48<01:57,  1.73s/it]

finance berhasil: 91

Scraping finance:  59%|███████████████████████████████████▏                        | 95/162 [02:50<01:58,  1.78s/it]

finance berhasil: 92

Scraping finance:  59%|███████████████████████████████████▌                        | 96/162 [02:52<01:52,  1.70s/it]

finance berhasil: 93

Scraping finance:  60%|███████████████████████████████████▉                        | 97/162 [02:54<01:55,  1.78s/it]

finance berhasil: 94

Scraping finance:  60%|████████████████████████████████████▎                       | 98/162 [02:55<01:50,  1.73s/it]

finance berhasil: 95

Scraping finance:  61%|████████████████████████████████████▋                       | 99/162 [02:57<01:55,  1.83s/it]

finance berhasil: 96

Scraping finance:  62%|████████████████████████████████████▍                      | 100/162 [02:59<01:44,  1.68s/it]

finance berhasil: 97

Scraping finance:  62%|████████████████████████████████████▊                      | 101/162 [03:00<01:38,  1.62s/it]

finance berhasil: 98

Scraping finance:  63%|█████████████████████████████████████▏                     | 102/162 [03:01<01:33,  1.56s/it]

finance berhasil: 99

Scraping finance:  64%|█████████████████████████████████████▌                     | 103/162 [03:03<01:45,  1.78s/it]

finance berhasil: 100

In [14]:
data_semua = data_sport + data_finance

df = pd.DataFrame(data_semua)

In [15]:
print("Total data:", len(df))
print("\nJumlah data berdasarkan label:")
print(df["label"].value_counts())

Total data: 200

Jumlah data berdasarkan label:
label
sport      100
finance    100
Name: count, dtype: int64

In [16]:
df.head(10)

                                          isi_berita  label
0  Dalam dua seri terakhir MotoGP 2027, Marc Marq...  sport
1  Alwi Farhan, Moh Zaki Ubaidillah dan Muhamad Y...  sport
2  Di tengah viral insiden cepirit pada ajang Hyr...  sport
3  Dejan Fedinansyah/Felisha Alberta Nathaniel Pa...  sport
4  Bagas Maulana/Apriyani Rahayu tak minder meski...  sport
5  Ajang lari bergengsi Alfamart Run 2026 siap di...  sport
6  Pasangan baru ganda campuran Dejan Ferdinansya...  sport
7  Grid MotoGP 2027 akhirnya lengkap. Senna Agius...  sport
8  Ganda putri Febriana Dwipuji Kusuma/Meilysa Tr...  sport
9  MotoGP 2026 berlanjut ke Austria akhir pekan i...  sport

In [17]:
df.shape

(200, 2)

In [18]:
df.columns

Index(['isi_berita', 'label'], dtype='str')

In [19]:
df.insert(
    0,
    "id",
    range(1, len(df) + 1)
)

In [20]:
df = df[
    [
        "id",
        "isi_berita",
        "label"
    ]
]

In [21]:
df.head()

   id                                         isi_berita  label
0   1  Dalam dua seri terakhir MotoGP 2027, Marc Marq...  sport
1   2  Alwi Farhan, Moh Zaki Ubaidillah dan Muhamad Y...  sport
2   3  Di tengah viral insiden cepirit pada ajang Hyr...  sport
3   4  Dejan Fedinansyah/Felisha Alberta Nathaniel Pa...  sport
4   5  Bagas Maulana/Apriyani Rahayu tak minder meski...  sport

In [22]:
print("Total data:", len(df))
print(df["label"].value_counts())

Total data: 200
label
sport      100
finance    100
Name: count, dtype: int64

In [23]:
df.head(10)

   id                                         isi_berita  label
0   1  Dalam dua seri terakhir MotoGP 2027, Marc Marq...  sport
1   2  Alwi Farhan, Moh Zaki Ubaidillah dan Muhamad Y...  sport
2   3  Di tengah viral insiden cepirit pada ajang Hyr...  sport
3   4  Dejan Fedinansyah/Felisha Alberta Nathaniel Pa...  sport
4   5  Bagas Maulana/Apriyani Rahayu tak minder meski...  sport
5   6  Ajang lari bergengsi Alfamart Run 2026 siap di...  sport
6   7  Pasangan baru ganda campuran Dejan Ferdinansya...  sport
7   8  Grid MotoGP 2027 akhirnya lengkap. Senna Agius...  sport
8   9  Ganda putri Febriana Dwipuji Kusuma/Meilysa Tr...  sport
9  10  MotoGP 2026 berlanjut ke Austria akhir pekan i...  sport

In [24]:
nama_file = "dataset_detik_200_berita.xlsx"

df.to_excel(
    nama_file,
    index=False
)

print(
    "File berhasil disimpan:",
    nama_file
)

File berhasil disimpan: dataset_detik_200_berita.xlsx