# Web Mining Menggunakan Trafilatura

## Pengumpulan Data Artikel Wikipedia

Pada praktikum ini dilakukan proses pengumpulan data dari Wikipedia menggunakan teknik web mining. Data yang dikumpulkan berupa 200 artikel dari Wikipedia.

Proses pengumpulan data dilakukan menggunakan Python, requests, dan Trafilatura. Setiap artikel akan diekstraksi menjadi data terstruktur yang terdiri dari judul, URL, teks artikel, dan jumlah kata.

In [1]:
%pip install pandas

Requirement already satisfied: pandas in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspaces/PPW/envwebmining/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import trafilatura
import pandas as pd
import time
import re

print("Library berhasil diimpor")

Library berhasil diimpor

## 1. Sumber Data

Sumber data yang digunakan dalam praktikum ini adalah Wikipedia Bahasa Indonesia.

Wikipedia digunakan sebagai sumber data karena artikel dapat diakses secara bebas melalui internet. Data yang dikumpulkan berupa artikel Wikipedia yang diperoleh melalui API Wikipedia.

Pada praktikum ini akan dikumpulkan sebanyak 200 artikel. Setiap artikel akan memiliki informasi berupa judul, URL, isi teks, dan jumlah kata.

In [3]:
api_url = "https://id.wikipedia.org/w/api.php"

params = {
    "action": "query",
    "list": "search",
    "srsearch": "teknologi",
    "srnamespace": 0,
    "srlimit": 200,
    "format": "json"
}

headers = {
    "User-Agent": "WebMiningStudent/1.0 (educational project)"
}

response = requests.get(
    api_url,
    params=params,
    headers=headers,
    timeout=30
)

print("Status Code:", response.status_code)

Status Code: 200

In [4]:
data = response.json()

hasil_pencarian = data["query"]["search"]

print("Jumlah artikel ditemukan:", len(hasil_pencarian))

Jumlah artikel ditemukan: 200

In [5]:
hasil_data = []

headers = {
    "User-Agent": "WebMiningStudent/1.0 (educational project)"
}

print("Persiapan ekstraksi selesai")

Persiapan ekstraksi selesai

In [6]:
api_url = "https://id.wikipedia.org/w/api.php"

params = {
    "action": "query",
    "list": "search",
    "srsearch": "teknologi",
    "srnamespace": 0,
    "srlimit": 200,
    "format": "json"
}

headers = {
    "User-Agent": "WebMiningStudent/1.0 (educational project)"
}

response = requests.get(
    api_url,
    params=params,
    headers=headers,
    timeout=30
)

print("Status Code:", response.status_code)

data = response.json()
hasil_pencarian = data["query"]["search"]

print("Jumlah artikel ditemukan:", len(hasil_pencarian))

Status Code: 200
Jumlah artikel ditemukan: 200

In [7]:
daftar_url = []

for item in hasil_pencarian:
    judul = item["title"]
    url = "https://id.wikipedia.org/wiki/" + judul.replace(" ", "_")
    
    daftar_url.append({
        "judul": judul,
        "url": url
    })

print("Jumlah URL:", len(daftar_url))

Jumlah URL: 200

In [8]:
hasil_data = []

print("Mulai proses ekstraksi...")

Mulai proses ekstraksi...

In [9]:
for i, item in enumerate(daftar_url, start=1):
    judul = item["judul"]
    url = item["url"]

    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=30
        )

        if response.status_code == 200:
            html = response.text

            teks = trafilatura.extract(
                html,
                include_comments=False,
                include_tables=False
            )

            if teks:
                jumlah_kata = len(teks.split())

                hasil_data.append({
                    "id": i,
                    "judul": judul,
                    "url": url,
                    "teks": teks,
                    "jumlah_kata": jumlah_kata
                })

                print(f"{i}/200 berhasil: {judul}")
            else:
                print(f"{i}/200 teks tidak ditemukan: {judul}")

        else:
            print(f"{i}/200 gagal ({response.status_code}): {judul}")

        time.sleep(0.5)

    except Exception as e:
        print(f"{i}/200 error: {e}")

1/200 berhasil: Teknologi
2/200 berhasil: Halaman Utama
3/200 berhasil: Institut Teknologi Bandung
4/200 berhasil: Sejarah teknologi
5/200 berhasil: YouTube
6/200 berhasil: Google
7/200 berhasil: Teknologi informasi komunikasi
8/200 berhasil: B. J. Habibie
9/200 berhasil: Kementerian Pendidikan Tinggi, Sains, dan Teknologi Republik Indonesia
10/200 berhasil: Teknologi informasi
11/200 berhasil: Sumatera Utara
12/200 berhasil: Yandex
13/200 berhasil: Kesehatan
14/200 berhasil: Teknologi finansial
15/200 berhasil: Teknologi pendidikan
16/200 berhasil: Informatika
17/200 berhasil: Institut Teknologi Sepuluh Nopember
18/200 berhasil: Teknologi olahraga
19/200 berhasil: Elang Mahkota Teknologi
20/200 berhasil: Tahap kesiapan teknologi
21/200 berhasil: Daerah Istimewa Yogyakarta
22/200 berhasil: Badan Pengkajian dan Penerapan Teknologi
23/200 berhasil: Revolusi Digital
24/200 berhasil: Universitas Teknologi Bandung
25/200 berhasil: Luhut Binsar Pandjaitan
26/200 berhasil: Sains dan teknologi di Indonesia
27/200 berhasil: Daftar Menteri Riset dan Teknologi Indonesia
28/200 berhasil: Energi surya
29/200 berhasil: Kecerdasan buatan
30/200 berhasil: Desa
31/200 berhasil: Balai Layanan Platform Teknologi
32/200 berhasil: Universitas Brawijaya
33/200 berhasil: Revolusi Industri
34/200 berhasil: Teknologi informasi Indonesia
35/200 berhasil: Richardus Eko Indrajit
36/200 berhasil: Windows Vista
37/200 berhasil: Kementerian Riset dan Teknologi Republik Indonesia
38/200 berhasil: Reini Wirahadikusumah
39/200 berhasil: Teknologi komunikasi digital
40/200 berhasil: Video
41/200 berhasil: 5G
42/200 berhasil: Telkomsel
43/200 berhasil: Universitas Indonesia
44/200 berhasil: Uni Soviet
45/200 berhasil: Yassierli
46/200 berhasil: Teknologi nuklir
47/200 berhasil: Universitas Gadjah Mada
48/200 berhasil: Brian Yuliarto
49/200 berhasil: Teknologi seluler
50/200 berhasil: Teknologi kesehatan
51/200 berhasil: Pengangguran teknologi
52/200 berhasil: Teknologi hijau
53/200 berhasil: Teknologi pengajaran
54/200 berhasil: Teknologi pangan
55/200 berhasil: Teknologi nuklir di Indonesia
56/200 berhasil: Honda PCX
57/200 berhasil: Generasi Z
58/200 berhasil: Antropologi teknologi
59/200 berhasil: Pusat kesehatan masyarakat
60/200 berhasil: Tap Talk Teknologi
61/200 berhasil: Teknologi dan masyarakat
62/200 berhasil: Determinisme teknologi
63/200 berhasil: Lembaga Pendidikan dan Pelatihan Kepolisian Negara Republik Indonesia
64/200 berhasil: Teknologi siluman
65/200 berhasil: Ricky Elson
66/200 berhasil: Teknologi pencari
67/200 berhasil: Institut Pertanian Bogor
68/200 berhasil: Polytron
69/200 berhasil: Perdagangan elektronik
70/200 berhasil: Mohammad Nuh
71/200 berhasil: Teknologi militer
72/200 berhasil: Taxi Maxim
73/200 berhasil: Universitas Telkom
74/200 berhasil: Kementerian Pendidikan Dasar dan Menengah Republik Indonesia
75/200 berhasil: Universitas Teknologi Rhein Westfalen Aachen
76/200 berhasil: Tatacipta Dirgantara
77/200 berhasil: Pidi Baiq
78/200 berhasil: Teknologi tinggi
79/200 berhasil: Industri 4.0
80/200 berhasil: Teknologi buku
81/200 berhasil: Budaya
82/200 berhasil: Telekomunikasi seluler di Indonesia
83/200 berhasil: Teknologi berbasis listrik
84/200 berhasil: Teknologi pertanian
85/200 berhasil: Telekomunikasi
86/200 berhasil: Universitas Andalas
87/200 berhasil: Lambang Tut Wuri Handayani
88/200 berhasil: Roket
89/200 berhasil: Hammam Riza
90/200 berhasil: Institut Teknologi Sumatera
91/200 berhasil: Revolusi Industri Keempat
92/200 berhasil: Waring Wera Wanua
93/200 berhasil: Apple Inc.
94/200 berhasil: Bambang Brodjonegoro
95/200 berhasil: Teknologi imersif
96/200 berhasil: Universitas Sanata Dharma
97/200 berhasil: Zaman Informasi
98/200 berhasil: Eri Cahyadi
99/200 berhasil: Teknokrasi
100/200 berhasil: School on Internet Asia
101/200 berhasil: Daftar pusat teknologi
102/200 berhasil: Institut Teknologi dan Bisnis Ahmad Dahlan Lamongan
103/200 berhasil: Kertas elektronik
104/200 berhasil: Papan tulis interaktif
105/200 berhasil: Audi
106/200 berhasil: Kode Morse
107/200 berhasil: Perusahaan teknologi
108/200 berhasil: Dioda pemancar cahaya organik
109/200 berhasil: Purnomo Yusgiantoro
110/200 berhasil: Sains dan teknologi di Filipina
111/200 berhasil: Organisasi Siswa Intra Sekolah
112/200 berhasil: Institut Teknologi Tangerang Selatan
113/200 berhasil: Produksi
114/200 berhasil: Digitisasi
115/200 berhasil: William Tanuwijaya
116/200 berhasil: Teknologi tepat guna
117/200 berhasil: Onno W. Purbo
118/200 berhasil: Ilmu
119/200 berhasil: Permainan
120/200 berhasil: Perguruan Tinggi Negeri Badan Hukum
121/200 berhasil: Unduh
122/200 berhasil: Badan Tenaga Atom Internasional
123/200 berhasil: Politeknik Teknologi Nuklir
124/200 berhasil: Perangkat keras
125/200 berhasil: Nadiem Makarim
126/200 berhasil: Roosseno Soerjohadikoesoemo
127/200 berhasil: Televisi
128/200 berhasil: Tabung sinar katode
129/200 berhasil: Teknologi kuno
130/200 berhasil: Tarrasmart Teknologi Indonesia
131/200 berhasil: Belva Devara
132/200 berhasil: Global System for Mobile Communications
133/200 berhasil: Universitas Jenderal Soedirman
134/200 berhasil: Hedy Lamarr
135/200 berhasil: Komputer
136/200 berhasil: Teknologi musik
137/200 berhasil: Institut Teknologi Kalimantan
138/200 berhasil: Institut Teknologi Nasional Bandung
139/200 berhasil: Muhammad Romahurmuziy
140/200 berhasil: Puteri Indonesia
141/200 berhasil: Institut Teknologi Garut
142/200 berhasil: Rachmad Gobel
143/200 berhasil: Masyarakat Jaringan
144/200 berhasil: Komputasi awan
145/200 berhasil: Prasanti Widyasih Sarli
146/200 berhasil: Korps Lalu Lintas
147/200 berhasil: Pengaruh teknologi terhadap anak-anak
148/200 berhasil: 4G
149/200 berhasil: Agroindustri
150/200 berhasil: Pemanufakturan
151/200 berhasil: Sekolah Tinggi Ilmu Kepolisian
152/200 berhasil: Kementerian Pertahanan Republik Indonesia
153/200 berhasil: Teknologi industri
154/200 berhasil: BMW
155/200 berhasil: Alexander Graham Bell
156/200 berhasil: Smartfren
157/200 berhasil: Bioteknologi
158/200 berhasil: Badan Pengembangan dan Pembinaan Bahasa
159/200 berhasil: Institut Teknologi Massachusetts
160/200 berhasil: Anime
161/200 berhasil: Cakram keras
162/200 berhasil: Ridwan Kamil
163/200 berhasil: Gelembung dot-com
164/200 berhasil: Rantai blok
165/200 berhasil: 1G
166/200 berhasil: Universitas Trisakti
167/200 berhasil: Sains, Teknologi, Rekayasa, dan Matematika
168/200 berhasil: Modernisasi
169/200 berhasil: Zulkieflimansyah
170/200 berhasil: Pusat panggilan
171/200 berhasil: WiMAX
172/200 berhasil: Otto Toto Sugiri
173/200 berhasil: Nurhayati Subakat
174/200 berhasil: Mobil
175/200 berhasil: Sistem informasi
176/200 berhasil: Institut Teknologi Petroleum Balongan
177/200 berhasil: Wakil Menteri Pendidikan Tinggi, Sains, dan Teknologi Indonesia
178/200 berhasil: Menteri Pendidikan Tinggi, Sains, dan Teknologi Indonesia
179/200 berhasil: Institut Teknologi PLN
180/200 berhasil: Soemantri Brodjonegoro
181/200 berhasil: Daftar Menteri Pendidikan Dasar dan Menengah Indonesia
182/200 berhasil: Achmad Zaky
183/200 berhasil: Magister
184/200 berhasil: Ilham Akbar Habibie
185/200 berhasil: Jaringan area lokal
186/200 berhasil: Institut Teknologi Padang
187/200 berhasil: I Nyoman Nuarta
188/200 berhasil: Set-top box
189/200 berhasil: Evolusi Jangka Panjang
190/200 berhasil: Mikrogenerasi
191/200 berhasil: Yudi Darma
192/200 berhasil: Pengendali jarak jauh
193/200 berhasil: Teknologi hipotetis
194/200 berhasil: Teknologi komunikasi autisme
195/200 berhasil: Moji
196/200 berhasil: Metalurgi
197/200 berhasil: Observatorium Bosscha
198/200 berhasil: Institut Teknologi Bacharuddin Jusuf Habibie
199/200 berhasil: Universitas Dipa Makassar
200/200 berhasil: Eddy Kusnadi Sariaatmadja

In [10]:
df = pd.DataFrame(hasil_data)

print("Jumlah data berhasil:", len(df))

Jumlah data berhasil: 200

In [11]:
df = pd.DataFrame(hasil_data)

print("Jumlah data berhasil:", len(df))

Jumlah data berhasil: 200

In [12]:
df.head()

,id,judul,url,teks,jumlah_kata
0,1,Teknologi,https://id.wikipedia.org/wiki/Teknologi,Teknologi\nTeknologi adalah penerapan pengetah...,10844
1,2,Halaman Utama,https://id.wikipedia.org/wiki/Halaman_Utama,Halaman Utama\nArtikel pilihan\nArchaeopteryx ...,464
2,3,Institut Teknologi Bandung,https://id.wikipedia.org/wiki/Institut_Teknolo...,Institut Teknologi Bandung\nInstitut Teknologi...,6661
3,4,Sejarah teknologi,https://id.wikipedia.org/wiki/Sejarah_teknologi,Sejarah teknologi\nSejarah teknologi mencakup ...,3259
4,5,YouTube,https://id.wikipedia.org/wiki/YouTube,YouTube\nYouTube adalah sebuah situs web berba...,9448

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           200 non-null    int64
 1   judul        200 non-null    str
 2   url          200 non-null    str
 3   teks         200 non-null    str
 4   jumlah_kata  200 non-null    int64
dtypes: int64(2), str(3)
memory usage: 7.9 KB

In [14]:
print("Jumlah baris:", len(df))
print("Jumlah kolom:", len(df.columns))

Jumlah baris: 200
Jumlah kolom: 5

In [15]:
df["jumlah_kata"].describe()

count      200.000000
mean      2487.655000
std       2945.955689
min        154.000000
25%        698.750000
50%       1405.000000
75%       2588.500000
max      23678.000000
Name: jumlah_kata, dtype: float64

In [16]:
df.sort_values(
    by="jumlah_kata",
    ascending=False
)[["judul", "jumlah_kata"]].head(10)

                                        judul  jumlah_kata
92                                 Apple Inc.        23678
117                                      Ilmu        15424
0                                   Teknologi        10844
21   Badan Pengkajian dan Penerapan Teknologi        10721
163                               Rantai blok        10373
56                                 Generasi Z         9664
4                                     YouTube         9448
155                                 Smartfren         9398
14                       Teknologi pendidikan         8740
132            Universitas Jenderal Soedirman         8662

In [17]:
df.sort_values(
    by="jumlah_kata",
    ascending=True
)[["judul", "jumlah_kata"]].head(10)

                          judul  jumlah_kata
90    Revolusi Industri Keempat          154
106        Perusahaan teknologi          164
49          Teknologi kesehatan          242
152          Teknologi industri          244
77             Teknologi tinggi          281
164                          1G          298
86   Lambang Tut Wuri Handayani          303
140    Institut Teknologi Garut          311
96              Zaman Informasi          347
162           Gelembung dot-com          367

In [18]:
df.to_csv(
    "data_200_wikipedia.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset berhasil disimpan.")

Dataset berhasil disimpan.

In [19]:
def bersihkan_teks(teks):
    teks = teks.lower()
    teks = re.sub(r'[^a-zA-ZÀ-ÿ\s]', ' ', teks)
    teks = re.sub(r'\s+', ' ', teks)
    return teks.strip()

df["teks_bersih"] = df["teks"].apply(bersihkan_teks)

print("Pembersihan teks selesai")

Pembersihan teks selesai

In [20]:
semua_kata = []

for teks in df["teks_bersih"]:
    semua_kata.extend(teks.split())

kata_unik = set(semua_kata)

print("Jumlah seluruh kata:", len(semua_kata))
print("Jumlah kata unik:", len(kata_unik))

Jumlah seluruh kata: 458239
Jumlah kata unik: 33584

In [23]:
list(kata_unik)[:33584]

['minikomputer',
 'malu',
 'terpisahkan',
 'contemporary',
 'telopon',
 'ira',
 'dimiliki',
 'ketrampilan',
 'kilometer',
 'pentek',
 'prisco',
 'bu',
 'pusaka',
 'engehalde',
 'ongisnade',
 'dibenahi',
 'memberitahu',
 'pong',
 'integration',
 'sormunen',
 'menjemur',
 'comments',
 'koivisto',
 'humanika',
 'cepat',
 'ghs',
 'batalyon',
 'recherche',
 'rambat',
 'penghormatan',
 'dubai',
 'bersertifikat',
 'liburan',
 'kadang',
 'tutupi',
 'samawi',
 'kompatible',
 'penelepon',
 'terpancar',
 'allocation',
 'literary',
 'orgasme',
 'merata',
 'balita',
 'adipati',
 'onnowiki',
 'yukiya',
 'mengatur',
 'santren',
 'soerachman',
 'raffi',
 'apla',
 'karachay',
 'writankar',
 'komunis',
 'architect',
 'wim',
 'umpamanya',
 'juara',
 'alkimia',
 'capkun',
 'azhar',
 'hmte',
 'botswana',
 'taeshukan',
 'javanese',
 'menginginkan',
 'brink',
 'akademia',
 'older',
 'alternatif',
 'takwa',
 'nhs',
 'akademikanya',
 'dault',
 'frida',
 'cs',
 'netratings',
 'newman',
 'lempeng',
 'casebeer',
 'newlpm',
 'zenobia',
 'kerjasama',
 'gallen',
 'unified',
 'pedagogis',
 'gerilya',
 'gallery',
 'memintasnya',
 'once',
 'penyusunan',
 'ignasius',
 'metal',
 'gang',
 'realism',
 'lap',
 'chosen',
 'nib',
 'eir',
 'bumn',
 'võimalused',
 'finally',
 'shank',
 'nurmalia',
 'pengantaran',
 'sukir',
 'berkobar',
 'sasli',
 'widjanarko',
 'puhakka',
 'brigadir',
 'larutan',
 'umumnya',
 'inkubasi',
 'menyalin',
 'mengakui',
 'berintegritas',
 'hebat',
 'juhana',
 'menolak',
 'marcia',
 'neal',
 'tapa',
 'ministry',
 'terpencil',
 'pcs',
 'ishmah',
 'selularku',
 'gc',
 'ganesa',
 'peraturan',
 'kolonialisme',
 'dimintai',
 'memori',
 'nata',
 'appeal',
 'mkv',
 'tegak',
 'agropole',
 'menyewa',
 'diva',
 'kakorlantas',
 'saettler',
 'pemaksaan',
 'subagyo',
 'bersusah',
 'rekonstruksi',
 'serap',
 'yusniantama',
 'ketentuan',
 'akt',
 'meminangnya',
 'transportasi',
 'gerbang',
 'menempel',
 'outwall',
 'evidence',
 'tehun',
 'bernilai',
 'klimont',
 'kenneth',
 'kumamoto',
 'romys',
 'kebayoran',
 'etika',
 'domaintools',
 'tremblay',
 'innovante',
 'customization',
 'buktikan',
 'damhil',
 'founders',
 'bojonegoro',
 'í',
 'gunungsitoli',
 'cambridge',
 'bbc',
 'kondusif',
 'nicolaus',
 'sibuasi',
 'representative',
 'anchiornis',
 'kacelnik',
 'cscl',
 'fraser',
 'nand',
 'windowsvista',
 'mendapati',
 'berpandangan',
 'fahriza',
 'perlawanan',
 'tpsa',
 'crossing',
 'ekslusif',
 'legalitas',
 'sempat',
 'karangwangkal',
 'approves',
 'pilihkan',
 'universitas',
 'baxter',
 'konklusif',
 'formula',
 'bertekanan',
 'plmn',
 'dikomersilkan',
 'unveils',
 'srigutomo',
 'az',
 'shekhar',
 'herausgeber',
 'bergabung',
 'katholik',
 'membutuhkannya',
 'rusmitantri',
 'revai',
 'kunkel',
 'tabib',
 'lontong',
 'anode',
 'enhancing',
 'psa',
 'ludens',
 'laoh',
 'afghanistan',
 'corr',
 'cary',
 'rangka',
 'restrictor',
 'obrador',
 'bocor',
 'halal',
 'musiman',
 'paypal',
 'qodar',
 'menuntut',
 'lakunya',
 'sri',
 'homogenisasi',
 'xplor',
 'tsung',
 'rts',
 'neoprene',
 'wage',
 'disedikna',
 'jabat',
 'palkovic',
 'beranjak',
 'nitrogen',
 'disusun',
 'pamudji',
 'version',
 'gutierrez',
 'institutes',
 'chapel',
 'trick',
 'setneg',
 'memperbarui',
 'senayan',
 'benturan',
 'literacy',
 'desc',
 'berselancar',
 'gt',
 'complexity',
 'equipment',
 'selayaknya',
 'terhingga',
 'penduga',
 'nonmanusia',
 'first',
 'syarief',
 'khusus',
 'mesin',
 'contained',
 'produksinya',
 'jd',
 'wrgb',
 'brian',
 'supriatna',
 'memprediksikan',
 'fathiyah',
 'discontinues',
 'jacqueline',
 'videografi',
 'disamakan',
 'berkeadilan',
 'pelecehan',
 'leichtbau',
 'allah',
 'bioindustri',
 'clech',
 'peritel',
 'serahkan',
 'thein',
 'careers',
 'gua',
 'thertina',
 'len',
 'tergolong',
 'segar',
 'konstruktivis',
 'merepresentasika',
 'amputasi',
 'pemenuhan',
 'rebecca',
 'buffett',
 'epidemiology',
 'jenisnya',
 'redesign',
 'negroponte',
 'repellent',
 'abon',
 'cryptozoology',
 'tone',
 'semudah',
 'singapura',
 'merrill',
 'akabri',
 'pad',
 'press',
 'bang',
 'increase',
 'takaendengan',
 'ponsel',
 'corona',
 'asmi',
 'angin',
 'kafeinanya',
 'statusnya',
 'memperingati',
 'filho',
 'softcopy',
 'treadmill',
 'law',
 'ubg',
 'berproliferasi',
 'tekmi',
 'diskusis',
 'jarang',
 'evangelism',
 'jtik',
 'nick',
 'posyandu',
 'tranggono',
 'arabcrunch',
 'crease',
 'berbatasan',
 'arithmetician',
 'telpon',
 'keeffe',
 'jauhary',
 'mc',
 'subir',
 'dielakkan',
 'pencakar',
 'zuhal',
 'longliveindonesia',
 'tf',
 'mulailah',
 'dikukuhkan',
 'pembangkang',
 'protein',
 'sandang',
 'pasundan',
 'pbl',
 'digitalisasi',
 'diakuisisinya',
 'menolong',
 'penting',
 'plat',
 'mallen',
 'sumita',
 'tersinkronisasi',
 'hermann',
 'memaksanya',
 'dominasi',
 'rivanno',
 'kesesuaian',
 'england',
 'sudarto',
 'gajinya',
 'devi',
 'diferensiasi',
 'authoritarian',
 'cliping',
 'kodel',
 'saldy',
 'almost',
 'mengizinkan',
 'hourani',
 'postgressql',
 'supercritical',
 'participation',
 'memediasi',
 'kerabat',
 'sinovac',
 'vonis',
 'hajraoui',
 'peresmian',
 'robots',
 'direlokasi',
 'batam',
 'minogue',
 'chaos',
 'wall',
 'ulmer',
 'diekstrak',
 'reproduction',
 'wuhub',
 'cryptocurrencies',
 'teknologis',
 'pompa',
 'named',
 'disubtitusi',
 'mangku',
 'memindahkannya',
 'auditorium',
 'chrisye',
 'seusia',
 'pengacara',
 'terkait',
 'veronika',
 'beruntun',
 'thu',
 'lakukan',
 'fortaleza',
 'atmosfer',
 'hancur',
 'widiyastuti',
 'gha',
 'didayagunakan',
 'macchu',
 'paraphrase',
 'phase',
 'mengada',
 'ceramah',
 'yurisdiksi',
 'rigidity',
 'osi',
 'rna',
 'canadian',
 'fdd',
 'berabad',
 'spectrum',
 'bayinya',
 'dinding',
 'hiroshima',
 'fraunhofer',
 'setan',
 'berbusana',
 'geofisika',
 'hmdi',
 'pemusat',
 'dibiayai',
 'biokimiawi',
 'kawin',
 'nonlogam',
 'littlefield',
 'wa',
 'leap',
 'diiklankan',
 'far',
 'wardani',
 'pemecahannya',
 'himakasi',
 'oaks',
 'geografi',
 'bujur',
 'kausalitas',
 'aini',
 'islamic',
 'perkembangan',
 'highman',
 'kealumnian',
 'pkpu',
 'os',
 'natge',
 'voyager',
 'adelaar',
 'penggeraknya',
 'erlich',
 'heddy',
 'redevance',
 'twintigsten',
 'sejahtera',
 'field',
 'marwah',
 'propr',
 'hazards',
 'evangelists',
 'elektrolisis',
 'polished',
 'todung',
 'maulina',
 'osip',
 'loker',
 'mixing',
 'dokumen',
 'superbrands',
 'lampu',
 'gelbstein',
 'menginjakan',
 'tool',
 'jijik',
 'keesokan',
 'degradasi',
 'advokasi',
 'pazdernik',
 'bartolic',
 'freezing',
 'internet',
 'christine',
 'pita',
 'pencerahan',
 'konstruktivisme',
 'pemasukan',
 'tesler',
 'idate',
 'praeger',
 'alik',
 'paru',
 'tokobagus',
 'langgar',
 'sumbangan',
 'korika',
 'itpb',
 'grasindo',
 'jamu',
 'eine',
 'mencegahnya',
 'supreme',
 'menebus',
 's',
 'garut',
 'tt',
 'stmb',
 'lawatan',
 'eksekusi',
 'nadim',
 'jushinry',
 'causing',
 'dial',
 'kesiapannya',
 'sadayuki',
 'cimahi',
 'silvertooth',
 'powershell',
 'sopiyana',
 'sejagad',
 'memulihkan',
 'ukur',
 'vfrcimflpar',
 'ub',
 'nbcu',
 'saul',
 'liku',
 'duawulu',
 'dede',
 'troena',
 'sapient',
 'mengingat',
 'deinterlace',
 'yusri',
 'ticker',
 'optimum',
 'contracting',
 'selective',
 'dicky',
 'purwarianti',
 'motorcycles',
 'kbb',
 'roeslan',
 'himda',
 'contonya',
 'sudan',
 'efisien',
 'canada',
 'founding',
 'tertib',
 'dinonaktifkan',
 'kontainer',
 'djalil',
 'individualisasi',
 'soekrisno',
 'huynh',
 'series',
 'verizon',
 'winardi',
 'diambil',
 'hadyan',
 'serm',
 'giliran',
 'mutiplexing',
 'spaceplace',
 'visioner',
 'beliebigen',
 'warber',
 'diskursus',
 'diupah',
 'menyaingi',
 'icter',
 'purnawirawan',
 'ilyas',
 'redman',
 'balau',
 'rob',
 'dei',
 'djokosoetono',
 'watched',
 'unidirectional',
 'default',
 'berdiskusi',
 'depledge',
 'danial',
 'commons',
 'roma',
 'exceptional',
 'gista',
 'analitika',
 'modest',
 'diakibatkan',
 'caltex',
 'dilapangan',
 'berjenjang',
 'bertuga',
 'ai',
 'novanto',
 'soedirman',
 'hedwig',
 'aromaterapi',
 'menparpostel',
 'selandia',
 'ix',
 'berlaku',
 'menang',
 'widiyana',
 'adya',
 'music',
 'touring',
 'ebert',
 'shing',
 'voyage',
 'saragih',
 'dibangun',
 'boston',
 'rotasi',
 'majalah',
 'anglo',
 'itg',
 'georgia',
 'kontennya',
 'provokatif',
 'modelling',
 'knol',
 'per',
 'artha',
 'clickbait',
 'infomasi',
 'subterranean',
 'fitz',
 'dibicarakan',
 'perang',
 'parabolanya',
 'meminimalisir',
 'virgin',
 'mayur',
 'oneighturbo',
 'eddie',
 'partini',
 'photonic',
 'crgp',
 'comic',
 'netizen',
 'bates',
 'orisinal',
 'ciwa',
 'schueffel',
 'breasted',
 'genggam',
 'reklamasi',
 'menukar',
 'darma',
 'safira',
 'ones',
 'mencit',
 'klarifikasi',
 'aect',
 'farishi',
 'baikal',
 'nanti',
 'suspended',
 'menengok',
 'rssa',
 'berpancasila',
 'biak',
 'menentang',
 'budhyarto',
 'gmbh',
 'ruben',
 'kriteria',
 'siberia',
 'louis',
 'batin',
 'memex',
 'armor',
 'harmen',
 'beragamnya',
 'memililiki',
 'kencana',
 'informatics',
 'imbas',
 'diganti',
 'silindris',
 'himasper',
 'menguak',
 'sir',
 'fariz',
 'capek',
 'brains',
 'barat',
 'moraes',
 'hembus',
 'deliver',
 'diperlombakan',
 'dikoordinasi',
 'memproses',
 'deskriptif',
 'komisioner',
 'hitung',
 'donatella',
 'peroleh',
 'memetik',
 'tudi',
 'bakaran',
 'potongan',
 'differential',
 'fath',
 'muller',
 'spain',
 'gsm',
 'tumasjan',
 'satuan',
 'peradaban',
 'soemardjito',
 'pengidap',
 'mendoakan',
 'hastaloka',
 'trieste',
 'fundraising',
 'ventilasi',
 'pilkades',
 'stanley',
 'kun',
 'ackley',
 'educating',
 'depends',
 'aurangabad',
 'forty',
 'ukmr',
 'card',
 'benediktus',
 'calvary',
 'uktn',
 'pengemudi',
 'eckert',
 'keberlangsungan',
 'yaitu',
 'spires',
 'vegetatif',
 'pengadilan',
 'darrigol',
 'resepsi',
 'kepler',
 'toan',
 'costumer',
 'abduh',
 'moscartello',
 'sejauh',
 'peningkatan',
 'eads',
 'conn',
 'astoto',
 'dikabarkan',
 'jaar',
 'tarung',
 'jernih',
 'abstraknya',
 'mcc',
 'dalamnya',
 'hyderabad',
 'pengurasan',
 'mentoring',
 'prop',
 'rezha',
 'sony',
 'rare',
 'brest',
 'cnc',
 'roeb',
 'olivastro',
 'concession',
 'trial',
 'merati',
 'menempati',
 'penghargaan',
 'hmbd',
 'menembus',
 'contest',
 'pemberdayaan',
 'mobility',
 'powered',
 'cooper',
 'mandela',
 'bappeko',
 'dilapisi',
 'sortasi',
 'listing',
 'zat',
 'kn',
 'popularisasi',
 'ujian',
 'sukiman',
 'padanya',
 'tzempelikos',
 'papilaya',
 'bergula',
 'dac',
 'kapulaga',
 'flash',
 'digenjot',
 'smil',
 'mufid',
 'lektor',
 'id',
 'jep',
 'berkumpul',
 'pengecoran',
 'zirst',
 'fisiknya',
 'ditungkatkan',
 'textured',
 'dalton',
 'lam',
 'bicet',
 'menganjurkan',
 'grossi',
 'ishaq',
 'kulon',
 'internetnya',
 'memberontak',
 'stall',
 'ginantra',
 'kuil',
 'centers',
 'hurocup',
 'nahdudin',
 'believing',
 'mohammed',
 'ketentraman',
 'ever',
 'rapidly',
 'vazire',
 'haiwan',
 'daytona',
 'irphan',
 'sets',
 'didirikanlah',
 'gununganyar',
 'karawitan',
 'meriahkan',
 'doni',
 'sdo',
 'batua',
 'mikrokapsul',
 'featuring',
 'interlaced',
 'aimed',
 'thompson',
 'habisan',
 'jano',
 'resolusi',
 'mengadposi',
 'sofyan',
 'rspta',
 'pertiwi',
 'randomization',
 'airnav',
 'starter',
 'seller',
 'skat',
 'hashcash',
 'diretas',
 'enggar',
 'diverifikasi',
 'fernanda',
 'chatbot',
 'galilei',
 'markoff',
 'hara',
 'desert',
 'kabarindonesia',
 'story',
 'mauss',
 'adiono',
 'debra',
 'wp',
 'moira',
 'strateginya',
 'st',
 'sebauh',
 'icic',
 'kontinen',
 'klorida',
 'plaza',
 'beluk',
 'xirka',
 'macquarie',
 'harapanrakyat',
 'memperbaharui',
 'mika',
 'load',
 'tadesse',
 'kanal',
 'porta',
 'americium',
 'fluid',
 'up',
 'resmikan',
 'rintisan',
 'mahtani',
 'angklung',
 'ksi',
 'tubefilter',
 'yasmi',
 'fauna',
 'pakar',
 'sugar',
 'corporate',
 'beni',
 'diperkecil',
 'onk',
 'persaingan',
 'aristoteles',
 'scheibe',
 'keprajan',
 'sofreh',
 'nate',
 'stage',
 'ed',
 'kategori',
 'begitu',
 'philoponus',
 'deficit',
 'obligasi',
 'kanada',
 'beriman',
 'wfm',
 'sastrapratedja',
 'lkis',
 'pierre',
 'distributed',
 'ellya',
 'classics',
 'orientation',
 'pemanenan',
 'foreign',
 'memliki',
 'crunchbase',
 'kesepuluh',
 'munir',
 'soeharto',
 'surface',
 'swinburn',
 'walled',
 'gulp',
 'days',
 'netherlands',
 'goride',
 'kepadatan',
 'heisler',
 'overheating',
 'multispektral',
 'kontak',
 'bibliografi',
 'stuart',
 'richardus',
 'patogen',
 'iwork',
 'ta',
 'analitikal',
 'pikiran',
 'peluncurannya',
 'keddadouche',
 'gerbaru',
 'silicon',
 'dna',
 'table',
 'ganeshatv',
 ...]

In [22]:
from collections import Counter

frekuensi_kata = Counter(semua_kata)

frekuensi_kata.most_common(20)

[('dan', 11774),
 ('yang', 9630),
 ('tanggal', 6506),
 ('di', 6358),
 ('pada', 4685),
 ('sunting', 4654),
 ('dari', 4579),
 ('dengan', 4207),
 ('untuk', 3802),
 ('teknologi', 3770),
 ('dalam', 3760),
 ('diakses', 3387),
 ('ini', 2742),
 ('sumber', 2646),
 ('tahun', 2527),
 ('cite', 2524),
 ('indonesia', 2411),
 ('the', 1920),
 ('sebagai', 1852),
 ('web', 1845)]